// SPDX-License-Identifier: LGPL-3.0-or-later OR MIT

#ifndef CODEXUI_CODEX_INTERNALPROTOCOLOPERATIONS_H
#define CODEXUI_CODEX_INTERNALPROTOCOLOPERATIONS_H

#include <ai/openai/codex/protocol/generated/ProtocolTypes.h>

#include <string_view>

namespace codexui::codex::internal_protocol {

namespace server_notifications {

// Codex exports typed payloads for these internal notifications but
// intentionally omits public operation descriptors. Keep only that operation
// identity here; payload shape remains generated by AISuite.
struct RawResponseItemCompleted final {
  static constexpr std::string_view method = "rawResponseItem/completed";
  using Params =
      ai::openai::codex::generated::v2::RawResponseItemCompletedNotification;
  static constexpr bool paramsRequired = true;
};

struct RawResponseCompleted final {
  static constexpr std::string_view method = "rawResponse/completed";
  using Params =
      ai::openai::codex::generated::v2::RawResponseCompletedNotification;
  static constexpr bool paramsRequired = true;
};

} // namespace server_notifications
} // namespace codexui::codex::internal_protocol

#endif // CODEXUI_CODEX_INTERNALPROTOCOLOPERATIONS_H
